### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [Alyetama/lolpoke#1]
Hi, what license is associated with your code? Is it also MIT like the Pokefetch project that inspired you to create this?

**Comment by Alyetama** [comment]
Hi @LifeCANvs,
Yes! I added a license file to the repo.

**Comment by LifeCANvs** [comment]
> Hi @LifeCANvs, Yes! I added a license file to the repo.

Thank you so much! I teach Computing classes to kids and teens and this will be a very nice Python project for them to explore and experiment with, because they mostly like Pokemon, so it will be interesting to them...

**Comment by Alyetama** [comment]
> > Hi @LifeCANvs, Yes! I added a license file to the repo.
> 
> Thank you so much! I teach Computing classes to kids and teens and this will be a very nice Python project for them to explore and experiment with, because they mostly like Pokemon, so it will be interesting to them...

That sounds great! Awesome!
